services:
  webserver:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./src:/app/src
      - ./config/nginx/nginx.frontend.conf:/etc/nginx/conf.d/frontend.conf
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./logs/nginx:/var/log/nginx/
    networks:
      - backend

  php:
    build: ./docker/php
    user: "www-data:www-data"
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "api.laravel.test:host-gateway"
    volumes:
      - ./src:/app/src
      - ./config/php/php.ini:/usr/local/etc/php/php.ini
      - ./config/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    environment:
      PHP_SESSION_HANDLER: "memcached"
      PHP_SESSION_PATH: "memcached:11211"
      PHP_ENABLE_XDEBUG: ${PHP_ENABLE_XDEBUG}
      XDEBUG_CONFIG: ${XDEBUG_CONFIG}
      PHP_IDE_CONFIG: ${PHP_IDE_CONFIG}
    networks:
      - backend

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@pg.sql"
      PGADMIN_DEFAULT_PASSWORD: "example"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    networks:
      - backend

volumes:
  pgdata:
  pgadmin-data:

networks:
  backend:
    driver: bridge
